Add files via upload
I had to tweak the data frames a little bit since I was receiving errors such as 
Error: unexpected invalid token in "Name <- c("Jeb", “"
or
Error: unexpected symbol in "ABC political"
then I made it work.